### ISSUE TITLE
win11 run error

### ISSUE THREAD

**Issue by m986883511** [jwise/pyusbip#2]
env: win11 python env and run it in administrator

```shell
(test) PS C:\Users\zero\Desktop\pyusbip> python .\pyusbip.py
Traceback (most recent call last):
  File ".\pyusbip.py", line 418, in <module>
    for fd, events in usbctx.getPollFDList():
  File "C:\Users\zero\miniconda3\envs\test\lib\site-packages\usb1\__init__.py", line 2123, in wrapper
    return func(self, *args, **kw)
  File "C:\Users\zero\miniconda3\envs\test\lib\site-packages\usb1\__init__.py", line 2344, in getPollFDList
    raise OSError(errno)
OSError: 1060
(test) PS C:\Users\zero\Desktop\pyusbip> python --version
Python 3.8.16
(test) PS C:\Users\zero\Desktop\pyusbip> pip list
Package    Version
---------- -------
libusb1    3.0.0
pip        23.0.1
setuptools 66.0.0
wheel      0.38.4
```

microsoft say this from [link](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--1000-1299-)
```text
ERROR_SERVICE_DOES_NOT_EXIST

1060 (0x424)

The specified service does not exist as an installed service.

```

I dont known what error?

a question, other usbip in win need install a testing driver, does it need?

**Comment by jwise** [comment]
Oo, very interesting.  I think it probably won't work on Windows because "[the use of libusb file descriptors with poll() on cygwin is NOT supported](https://github.com/libusb/libusb/wiki/Windows#How_to_use_libusb_on_Windows)"?

But maybe you could rewrite it to put the libusb stuff in a thread instead and communicate through a channel, instead?  You'd also have to install the libusb driver (see the above linked wiki page), of course.
